### ISSUE TITLE
!odoo today does not reconnect to Odoo

### ISSUE THREAD

**Issue by pmauduit** [pmauduit/slack-bot#23]
```
17:52:27.744 [Grizzly(1)] ERROR fr.spironet.slackbot.listeners.OdooListener - Error occured
fr.spironet.slackbot.odoo.DisconnectedFromOdooException: null
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:318)
	at fr.spironet.slackbot.odoo.OdooClient.getAttendances(OdooClient.groovy:20)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:318)
	at fr.spironet.slackbot.listeners.OdooListener.totalTimeToday(OdooListener.groovy:178)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:318)
	at fr.spironet.slackbot.listeners.OdooListener.onEvent(OdooListener.groovy:266)
```

it should try/catch the exception here:

* https://github.com/pmauduit/slack-bot/blob/master/src/main/groovy/fr/spironet/slackbot/listeners/OdooListener.groovy#L142
* https://github.com/pmauduit/slack-bot/blob/master/src/main/groovy/fr/spironet/slackbot/listeners/OdooListener.groovy#L178
* https://github.com/pmauduit/slack-bot/blob/master/src/main/groovy/fr/spironet/slackbot/listeners/OdooListener.groovy#L216

Or maybe at a higher level (into the onEvent ?)

**Comment by pmauduit** [comment]
seems that a reconnect is attempted on each command of the odoo listener, closing.
