### ISSUE TITLE
slack channel being lost

### ISSUE THREAD

**Issue by pmauduit** [pmauduit/slack-bot#26]
Encountered the following stacktrace in the logs today:

```
11:15:12.722 [GithubScheduledService RUNNING] ERROR fr.spironet.slackbot.scheduled.GithubScheduledService - error occured while getting the notifications from Github
java.lang.IllegalArgumentException: Channel can't be null
        at com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl.sendMessage(SlackWebSocketSessionImpl.java:568)
        at com.ullink.slack.simpleslackapi.impl.AbstractSlackSessionImpl.sendMessage(AbstractSlackSessionImpl.java:198)
        at com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl.sendMessageToUser(SlackWebSocketSessionImpl.java:181)
        at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:318)
        at fr.spironet.slackbot.scheduled.GithubScheduledService.notifyEvent(GithubScheduledService.groovy:158)
```

**Comment by pmauduit** [comment]
looks very specific to this `sendMessageToUser` call, and this is not systematic, sometimes the same code path has no issue with calling this method (and actually sending message to the user).

**Comment by pmauduit** [comment]
Seems that it comes from the slack library I'm using. the SlackUser object is correctly found, but the API is unable to find the related private conversation between the bot and the user.

```
SlackWebSocketSessionImpl:179:

    public SlackMessageHandle<SlackMessageReply> sendMessageToUser(SlackUser user, SlackPreparedMessage message) {
        SlackChannel iMChannel = getIMChannelForUser(user);
        return sendMessage(iMChannel, message);
    }

SlackWebSocketSessionImpl:211:

    private SlackChannel getIMChannelForUser(SlackUser user) {
        List<SlackChannel> imcs = getAllIMChannels();
        for (SlackChannel channel : imcs) {
            if (channel.getMembers().contains(user)) {   // <- there is an expected channel, but still we never meet this condition
                return channel;
            }
        }
        SlackMessageHandle<SlackChannelReply> reply = openDirectMessageChannel(user); // <- does not work either
        return reply.getReply().getSlackChannel();
    }
```

**Comment by pmauduit** [comment]
I've got a workaround by looking up the slack channel by hand, like:
```
        def expectedChan = this.slackSession.getChannels().find {
            it.direct == true &&
                it.getMembers().find { sl -> sl.userMail == this.botOwnerEmail } != null
        }
        if (expectedChan == null) {
            logger.error("Unable to find the channel in which to send the notification, giving up")
            return
        }
        this.slackSession.sendMessage(expectedChan, msg)
```

**Comment by pmauduit** [comment]
Still missing every times the `BOT_OWNER_EMAIL` env variable is used:

* Confluence service
* GoogleCal job
* Jira RSS service
* Jira service
* Tempo Timesheet Validation service
* Terraform service

**Comment by pmauduit** [comment]
need to fix the testsuite now though ...

**Comment by pmauduit** [comment]
done by introducing a SlackWorkaround class to lookup myself the expected channel to use.
