### ISSUE TITLE
gdrive c2c planning command - bad request - unable to parse range

### ISSUE THREAD

**Issue by pmauduit** [pmauduit/slack-bot#50]
```
11:27:38.790 [Grizzly(2)] ERROR fr.spironet.slackbot.listeners.GDriveListener - Error occurred processing the command, returning usage()
com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request
{
  "code" : 400,
  "errors" : [ {
    "domain" : "global",
    "message" : "Unable to parse range: June 19 - June 30 [week 25&26]!@:@",
    "reason" : "badRequest"
  } ],
  "message" : "Unable to parse range: June 19 - June 30 [week 25&26]!@:@",
  "status" : "INVALID_ARGUMENT"
}
        at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:146)
        at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
        at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:321)
        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1065)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
        at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:318)
        at fr.spironet.slackbot.google.C2CGeospatialPlanning.getDaysAllocated(C2CGeospatialPlanning.groovy:148)

```

**Comment by pmauduit** [comment]
Anyway, using the command generally gives the wrong sheet (the one from the previous sprint).
