### ISSUE TITLE
Unable to get new issues on JIRA

### ISSUE THREAD

**Issue by pmauduit** [pmauduit/slack-bot#8]
```
java.lang.ClassCastException: class com.ullink.slack.simpleslackapi.replies.SlackReplyImpl cannot be cast to class com.ullink.slack.simpleslackapi.replies.SlackChannelReply (com.ullink.slack.simpleslackapi.replies.SlackReplyImpl and com.ul
link.slack.simpleslackapi.replies.SlackChannelReply are in unnamed module of loader groovy.lang.GroovyClassLoader @6d4d66d2)
        at com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl.getIMChannelForUser(SlackWebSocketSessionImpl.java:168) ~[simpleslackapi-1.2.0.jar:na]
        at com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl.sendMessageToUser(SlackWebSocketSessionImpl.java:134) ~[simpleslackapi-1.2.0.jar:na]
        at com.ullink.slack.simpleslackapi.SlackSession$sendMessageToUser$2.call(Unknown Source) ~[na:na]
        at fr.spironet.slackbot.scheduled.JiraScheduledService.runOneIteration(JiraScheduledService.groovy:82) ~[slackbot.groovy:na]
        at com.google.common.util.concurrent.AbstractScheduledService$ServiceDelegate$Task.run(AbstractScheduledService.java:193) ~[guava-25.0-jre.jar:na]
```

Note: the same failing cast arises in the GithubScheduledService as well:

```
11:52:36.888 [GithubScheduledService RUNNING] ERROR f.s.s.s.GithubScheduledService - error occured while getting the notifications from Github
java.lang.ClassCastException: class com.ullink.slack.simpleslackapi.replies.SlackReplyImpl cannot be cast to class com.ullink.slack.simpleslackapi.replies.SlackChannelReply (com.ullink.slack.simpleslackapi.replies.SlackReplyImpl and com.ul
link.slack.simpleslackapi.replies.SlackChannelReply are in unnamed module of loader groovy.lang.GroovyClassLoader @6d4d66d2)
        at com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl.getIMChannelForUser(SlackWebSocketSessionImpl.java:168) ~[simpleslackapi-1.2.0.jar:na]
        at com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl.sendMessageToUser(SlackWebSocketSessionImpl.java:134) ~[simpleslackapi-1.2.0.jar:na]
        at com.ullink.slack.simpleslackapi.SlackSession$sendMessageToUser$2.call(Unknown Source) ~[na:na]
        at fr.spironet.slackbot.scheduled.GithubScheduledService.notifyEvent(GithubScheduledService.groovy:110) ~[slackbot.groovy:na]
```

**Comment by pmauduit** [comment]
I can't reproduce after having restarted my bot ...

**Comment by pmauduit** [comment]
Cannot reproduce, closing.
